### ISSUE TITLE
Docker version works on Windows, Compiled version throws NodePException error on Linux

### ISSUE THREAD

**Issue by Biogeographer** [ssolo/ALE#17]
The attached gene tree (G.tree) runs successfully in ALEobserve on both Windows and Linux systems yielding the expected output comprising marginal clade frequencies (G.trees.ale; attached from Windows). However, ALEmcmc_undated completes and exists normally on Windows but terminates with the error below on Linux.

>terminate called after throwing an instance of 'bpp::NodePException'
>what():  NodeException: Node::getDistanceToFather: Node has no distance.(id:0)

I assume this is an issue with the trees in my examples having no branch lengths. However, why does Windows allow trees without branch lengths for the undated algorithm, and Linux does not? 

I am running ALE v. 0.4 on Windows 10 Pro pulled from Docker and ALE v. 0.5 on a Linux Server running Centos 6.6. 

Thank you kindly!

[ale-example.zip](https://github.com/ssolo/ALE/files/2858170/ale-example.zip)

**Comment by neptuneyt** [comment]
I have the same problem, do you have any solution? Thanks a lot.

**Comment by ssolo** [comment]
Sorry, don't know docker, maybe @Boussau can help!
