### ISSUE TITLE
bpp error in reading species tree

### ISSUE THREAD

**Issue by Jigyasa3** [ssolo/ALE#18]
My species tree is rooted but undated. So I am using ALEml_undated on my species tree and 1 gene tree.

code-
$ALEml_undated mtdna_copytwo_newlabel_rooted.nwk COG20525_individual.treefile.ale sample=10 separators=_ tau=0

Error- terminate called after throwing an instance of 'bpp::Exception'
  what():  TextTools::toDouble(). Invalid number specification: 3.675070999999974E-4
Aborted (core dumped)

I have tried saving my rooted tree (from Figtree) with node labels saved in decimal, roman, fractions format. But I keep getting an error of "invalid number specifications". 

Any suggestions?

**Comment by jtrew89** [comment]
Did you manage to fine a solution to this problem? I'm having a similar one.

**Comment by ophiomorus** [comment]
I am trying to run bpp 4.3.8. I inferred my Bayesian tree in Beast v. 10.4. Then, I  made Newik tree format in Figtree and used in my control file. Also I mad Imap file with tags (e.g.  ar1^arnol, ar2^arnol, ar3^arnol, etc.). But when I run bpp, the following error comes up and the analysis is terminated:
Parsing species tree...Labels (43) specified in --reorder do not match species tree (137)
Does anyone know how I can solve this problem?

**Comment by Jigyasa3** [comment]
@jtrew89 and @ophiomorus  , I was able to solve the problem. FIGTREE converts the bootstrap support to scientific notation (3.675070999999974E-4), but if you use the nwk file directly from the software of choice (eg.BEAST consensus tree), then it works.
