### ISSUE TITLE
Boost issues in conda

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [ssolo/ALE#20]
Hello,
I'm trying to create a conda env compatible with building ALE. I'm encountering different flavors of issues with different flavor of  boost.
I'am unsure if these can be fixed in a way which does not necessitate to repackage boost manually, but maybe these errors can be easily solved, as I am not proficient in the way of cpp building.
With 1.60<=Boost<1.70, I get a cmake file issue stating : 
`Could not find the following static Boost libraries   boost_mpi `
using the `-DBUILD_STATIC=OFF` flag doesn't change anything
With Boost=1.70, cmake works, but when building anything related to boost I get : 
```
undefined reference to `boost::mpi::communicator::operator ompi_communicator_t*() const'
undefined reference to `boost::archive::detail::basic_iarchive::basic_iarchive(unsigned int)'
....
```
and this go on with all call to boost functions.
With Boost>1.70, the cmake step fail with:
```
CMake Error at /home/ubuntu/miniconda3/envs/ALE/lib/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /home/ubuntu/miniconda3/envs/ALE/lib/cmake/boost_mpi-1.74.0/boost_mpi-config.cmake

  but it set boost_mpi_FOUND to FALSE so package "boost_mpi" is considered to
  be NOT FOUND.  Reason given by package:

  No suitable build variant has been found
```
Here is the minimal conda env yaml file I'm using and you can test this env with : 
conda env create -f [ale.yaml](https://github.com/ssolo/ALE/files/5642840/ale.txt)

**Comment by boradiril** [comment]
did u manage to solve this issue?

**Comment by ssolo** [comment]
Sorry I cannot help with this.
