### ISSUE TITLE
mpi still required for build

### ISSUE THREAD

**Issue by EricDeveaud** [ssolo/ALE#22]
Hello, 

commit https://github.com/ssolo/ALE/commit/f265cfb777d30f4d98cb154859df341f0b459415  removed openmpi dependent targets. but build still requires openmpi due to boost mpi find_package usage

changing 
`find_package(Boost COMPONENTS mpi serialization REQUIRED)`
to 
`find_package(Boost COMPONENTS serialization REQUIRED)`

allows build to succed without openmpi.

regards

Eric

**Comment by ssolo** [comment]
This should be resolved, please verify.
