### ISSUE TITLE
Error when compiling ALE

### ISSUE THREAD

**Issue by 007goodmans** [ssolo/ALE#23]
when i compile the ALE，there are some errors. I have try to rebuilt Bio++ many times, but it still comes out. Does anybody know how to solve this. 
![QQ图片20210321191804](https://user-images.githubusercontent.com/53086066/111902814-2e28c880-8a7a-11eb-8b68-ef24cf6e3483.png)

**Comment by drenal** [comment]
Hi,
please try the latest commit with ` -DBUILD_STATIC=OFF ` cmake flag.

**Comment by 007goodmans** [comment]
We have solved this problem, thank you very much for your help.

**Comment by xxl97** [comment]
Hi,
We also had this problem and the above solution didn't work for me, so how did you solve it?
thanks for your help.
