### ISSUE TITLE
genefamily.tree file format

### ISSUE THREAD

**Issue by Qiaojilim** [ssolo/ALE#25]
hello,

I am running ALE analysis for my one genefamily tree file but it shows an error like :

Error: gene name Nandina_domestica_13764 is associated to species name Nandina that cannot be found in the species tree.

so I am wondering could you specify the criteria to construct genefamily.tree file ? I think the error is from some gene names ot included in species tree file. should all the gene name of genefamily.tree same as the species name of the species tree file? 

thanks for your help.

Qiaoji

**Comment by ssolo** [comment]
By default the separator is an underscore ("_"), cf. ALE/example_data/, this can be changed with the 'seperators' flag.
