### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Jigyasa3** [ssolo/ALE#26]
Hi @ssolo 

I am able to run `Aleml_undated` on most of my trees, but somehow for some trees, the aleml analysis begins but stops in between giving a segmentation fault error.

Code-
`#burnin
singularity exec /home/j/jigyasa-arora/local/ale.sif ALEobserve symbionttree-d__Bacteria_p__Fibrobacterota__p__Bacteroidota__p__UBP14__COG0552_tips_2.nwk

#run ALEml_undated
singularity exec /home/j/jigyasa-arora/local/ale.sif ALEml_undated 2-hosttree-d__Bacteria_p__Fibrobacterota__p__Bacteroidota__p__UBP14__COG0552_tips_2.nwk symbionttree-d__Bacteria_p__Fibrobacterota__p__Bacteroidota__p__UBP14__COG0552_tips_2.nwk.ale sample=10
`

Files- [species tree ](https://github.com/Jigyasa3/errors/blob/master/2-hosttree-d__Bacteria_p__Desulfobacterota__p__SZUA79__p__UBA10199__COG0552_tips_2.nwk), [genetree](https://github.com/Jigyasa3/errors/blob/master/symbionttree-d__Bacteria_p__Desulfobacterota__p__SZUA79__p__UBA10199__COG0552_tips_2.nwk)

Error-
`Read species tree from: 2-hosttree-d__Bacteria_p__Desulfobacterota__p__SZUA79__p__UBA10199__COG0552_tips_2.nwk..
Read summary of tree sample for 1 trees from: symbionttree-d__Bacteria_p__Desulfobacterota__p__SZUA79__p__UBA10199__COG0552_tips_2.nwk.ale..
Reconciliation model initialised, starting DTL rate optimisation..
#optimizing delta rate
#optimizing tau rate
#optimizing lambda rate
#optimizing rates
Optimizing... - 46
ML rates:  delta=0.108325; tau=0.282899; lambda=0.20712.
LL=-103.615
Sampling reconciled gene trees..

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**********Segmentation fault
`

**Comment by maxemil** [comment]
I've had this problem before as well, but could not figure out how to solve it properly. A workaround for me was to try again (and again) with the same tree. Since the segfault seemed to occur randomly, at some point it would work....
To speed it up, you can specify the ML rates from the first run for the consecutive ones.

**Comment by Jigyasa3** [comment]
thank you, @maxemil!

**Comment by ssolo** [comment]
This should be fixed, please verify.
