### ISSUE TITLE
Install error: bpp-phyl required but not found

### ISSUE THREAD

**Issue by ssgituser** [ssolo/ALE#27]
When trying to install on a CentOS 8 server I get the following error:

CMake Error at CMakeLists.txt:48 (MESSAGE):
  bpp-phyl required but not found.
Call Stack (most recent call first):
  CMakeLists.txt:59 (IMPROVED_FIND_LIBRARY)

After running the command:

cmake .. -DBUILD_STATIC=OFF -DCMAKE_LIBRARY_PATH=/usr/local/software/BIO++/lib64/ -DCMAKE_INCLUDE_PATH=/usr/local/software/BIO++/include/

I have built the BIO++ package with the following option:

-DCMAKE_INSTALL_PREFIX=/usr/local/software/BIO++/

And I do see the various directories of lib and include populated

**Comment by drenal** [comment]
Hi,
please check it without the `-DBUILD_STATIC=OFF` as a first trial.

**Comment by ssgituser** [comment]
Have tried that, but no same error.

--
___________________________________________________
Sajesh Singh
Manager, Systems and Scientific Computing
American Museum of Natural History
200 Central Park West
New York, NY 10024

(O) (212) 313-7263
(C) (917) 763-9038
(E) ***@***.***
________________________________

**Comment by drenal** [comment]
Then please provide logs for both the ALE and the 3 bio++ packages installation in order to help you further.

**Comment by ssgituser** [comment]
Log files as requested.

**Comment by ssgituser** [comment]
Log files as requested.


[Ale-CMakeOutput.log](https://github.com/ssolo/ALE/files/8120125/Ale-CMakeOutput.log)
[Bio-Core-CMakeOutput.log](https://github.com/ssolo/ALE/files/8120126/Bio-Core-CMakeOutput.log)
[Bio-Phyl-CMakeOutput.log](https://github.com/ssolo/ALE/files/8120127/Bio-Phyl-CMakeOutput.log)
[Bio-Seq-CMakeOutput.log](https://github.com/ssolo/ALE/files/8120128/Bio-Seq-CMakeOutput.log)

**Comment by drenal** [comment]
Thanks, let's check ALE's CMakeCache.txt file too, are there the paths correct?

**Comment by ssgituser** [comment]
Certainly. File attached.

[CMakeCache.txt](https://github.com/ssolo/ALE/files/8125110/CMakeCache.txt)

Does not seem as though the paths are recognized to the BPP libraries/includes:

//Path to a file.
bpp-phyl_INCLUDE_DIR:PATH=bpp-phyl_INCLUDE_DIR-NOTFOUND

//Path to a library.
bpp-phyl_LIBRARY:FILEPATH=bpp-phyl_LIBRARY-NOTFOUND

**Comment by drenal** [comment]
Yes, and also the bpp-core and bpp-seq paths are missing, on our (Debian based) machines it's the following:
```
//Path to a file.
bpp-core_INCLUDE_DIR:PATH=/scratch/local/include

//Path to a library.
bpp-core_LIBRARY:FILEPATH=/scratch/local/lib/libbpp-core.a

//Path to a file.
bpp-phyl_INCLUDE_DIR:PATH=/scratch/local/include

//Path to a library.
bpp-phyl_LIBRARY:FILEPATH=/scratch/local/lib/libbpp-phyl.a

//Path to a file.
bpp-seq_INCLUDE_DIR:PATH=/scratch/local/include

//Path to a library.
bpp-seq_LIBRARY:FILEPATH=/scratch/local/lib/libbpp-seq.a

//Dependencies for the target
exODT_LIB_DEPENDS:STATIC=general;/scratch/local/lib/libbpp-phyl.a;general;/scratch/local/lib/libbpp-seq.a;general;/scratch/local/lib/libbpp-core.a;
```

According to CMake's documentation, one could try to set these paths in the CMakeCache.txt manually, but because other parameters are missing too (i.e. `boost_headers_DIR`, and other `boost_*`), I'm not sure it will be enough for a successful compilation.

Let's try another way, please create a new `ALE-build` directory (or delete everything in the current one) and then add the debug flag `-DCMAKE_FIND_DEBUG_MODE=true` to cmake, i.e. on our machine it would be:
```
cmake -DCMAKE_LIBRARY_PATH=/scratch/local/lib -DCMAKE_INCLUDE_PATH=/scratch/local/include -DCMAKE_FIND_DEBUG_MODE=true -DCMAKE_SYSTEM_PREFIX_PATH=/scratch/local -DCMAKE_INSTALL_PREFIX=/scratch/local ../ALE
```

**Comment by ssgituser** [comment]
Tried with the new DEBUG flag and it still failed. Looks like it does search the correct path for the BIO++ library:
/usr/local/software/BIO++/lib64/(lib)bpp-phyl(\.so|\.a)

And the file does exist:
ls -al /usr/local/software/BIO++/lib64/libbpp-phyl3.so
lrwxrwxrwx 1 root root 17 Feb 17 11:18 /usr/local/software/BIO++/lib64/libbpp-phyl3.so -> libbpp-phyl3.so.1


Cmake output log: 
[CMakeOutput.log](https://github.com/ssolo/ALE/files/8172488/CMakeOutput.log)

**Comment by ssgituser** [comment]
Just realized after sending message. I see that cmake is looking for
/usr/local/software/BIO++/lib64/libbpp-phyl.so

While I have:
/usr/local/software/BIO++/lib64/libbpp-phyl3.so

Is it that I have a too new version of BIO++ installed?

**Comment by drenal** [comment]
No, ALE supports bio++ v3, but at that time the library didn't get the `3` version-postfix yet.

I've updated the `CMakeLists.txt` file to search for both bio++ libraries (with and without the `3` postfix). 

Please do a `git pull` and try to recompile, I hope this time it will find the libraries.

**Comment by ssgituser** [comment]
Seems to be getting further, but now getting the following error:

 cmake3 .. -DBUILD_STATIC=OFF -DCMAKE_INCLUDE_PATH=/usr/local/software/BIO++/include/
CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Library bpp-phyl  found here:
   includes : bpp-phyl_INCLUDE_DIR-NOTFOUND
   library: /usr/local/software/BIO++/lib64/libbpp-phyl3.so
-- Library bpp-seq  found here:
   includes : /usr/local/software/BIO++/include
   library: /usr/local/software/BIO++/lib64/libbpp-seq3.so
-- Library bpp-core  found here:
   includes : /usr/local/software/BIO++/include
   library: /usr/local/software/BIO++/lib64/libbpp-core3.so
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
bpp-phyl_INCLUDE_DIR
   used as include directory in directory /usr/local/src/ALE
   used as include directory in directory /usr/local/src/ALE
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src
   used as include directory in directory /usr/local/src/ALE/src

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "exODT":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "ALEsample":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "ALEevaluate_undated":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "mlresampler_undated":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "ALEml":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "ALEcount":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "ALEmcmc_undated":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "ALEobserve":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "computeALEcomplexity":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "ALEadd":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "CCPscore":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "ls_leaves":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "ALEml_undated":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "ALEprune":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "simulation":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "times_undated":

    "bpp-phyl_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by drenal** [comment]
`includes : bpp-phyl_INCLUDE_DIR-NOTFOUND`  for some reason the bpp-phyl include files are not found. Are they there? (bpp-core and bpp-seq are there and found).

I would recompile just the bpp-phyl package, maybe something went wrong.

Let's try without the `-DBUILD_STATIC` flag too for now and the `-DCMAKE_LIBRARY_PATH` was not set, but the libraries were found, so probably this is not the cause of the problem.

**Comment by ssgituser** [comment]
No  luck same error after rebuilding bpp-phyl package

**Comment by drenal** [comment]
Hi,

BPP v3 is still under heavy development, so we've decided to only support BPP 2.4.1 (the last stable version of BPP). The master branch represents this state of ALE now, INSTALL.md 's build from source section is updated accordingly.

Alternatively a bppv3 branch was created which supports the BPP v3 in its state in September 2021: https://github.com/ssolo/ALE/tree/bppv3 
Please check the https://github.com/ssolo/ALE/blob/bppv3/etc/filesDockerImage/Dockerfile for instructions on how to make the compilation successful with this combination of versions.
