### ISSUE TITLE
Install Error: no matching function for call to bpp::Parameter::Parameter()

### ISSUE THREAD

**Issue by flass** [ssolo/ALE#28]
Hi Gergely & co.,

I've got his error when trying to compile ALE in an Ubuntu Bionic environment; see below. 

```
/home/ubuntu/software/ALE/src/ALEml.cpp: In constructor ‘p_fun::p_fun(exODT_model*, approx_posterior*, double, double, double, bool, bool, bool)’:
/home/ubuntu/software/ALE/src/ALEml.cpp:39:65: error: no matching function for call to ‘bpp::Parameter::Parameter(const char [6], double&, std::shared_ptr<bpp::IntervalConstraint>&)’
    addParameter_( new Parameter("delta", delta_start, constraint) ) ;
```

I first had this issue when trying to build this Docker image:
https://github.com/flass/pantagruel/blob/master/Dockerfile.

I could replicate it on a VM with Ubuntu Bionic OS 
on the VM, `uname -a` gives: 
```
Linux vibriocloud 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
I've installed this minimal set of debian packages to support the ALE dependencies:
```sh
sudo apt-get install -y --no-install-recommends libboost-dev libboost-serialization-dev libboost-mpi-dev  \
libbpp-core-dev libbpp-phyl-dev libbpp-seq-dev libbpp-seq-omics-dev
```
So I believe this makes the Bpp libs to be of the 2.4.0 version (see https://packages.ubuntu.com/ko/bionic/libbpp-core-dev)

I'm not too sure what has changed since last I compiled ALE successfully in this same environment.

Can you advise on a fix?

thanks in advance.

Best regards,

Florent
[bug_installation_ALE_bionic.txt](https://github.com/ssolo/ALE/files/8119982/bug_installation_ALE_bionic.txt)

**Comment by drenal** [comment]
Hi Florent,
we have changed the code in September last year to support the new [(unreleased) Bio++ library](https://github.com/BioPP/bppsuite/releases/tag/v3.0.0) , so I suspect this is causing the issue with the old Bio++ library.

Could you please check if you can compile ALE without these changes (the commit before the (currently) last commit)?
```
cd ALE
git checkout 168274f71ac819047e9cc446fc3608ae32789e27
# and then do a fresh cmake compile
```

Best,
Lenard

**Comment by flass** [comment]
Hi Lenard,

yes it builds correctly under this version. I've frozen this ALE version in my Dockerfile now.

thanks a lot!

Florent
