### ISSUE TITLE
Update the docker version?

### ISSUE THREAD

**Issue by michoug** [ssolo/ALE#29]
Hi,
Would it be possible to update the docker version to the last one?
Thanks!
Greg

**Comment by drenal** [comment]
Hi Greg,
a new Dockerfile have been just pushed for BPP v2.4.1: https://github.com/ssolo/ALE/blob/master/etc/filesDockerImage/Dockerfile

**Comment by michoug** [comment]
Thanks!

**Comment by michoug** [comment]
Hi
Would it be possible to put the image on docker hub to simplify its use?
Thanks
Greg

**Comment by ssolo** [comment]
Sorry, please ask @Boussau , I don't know docker.
