### ISSUE TITLE
bppexception during consensus tree calculation

### ISSUE THREAD

**Issue by 444thLiao** [ssolo/ALE#33]
Hi all

I meet an issue during calculating the consensus tree.

```
Results in: xmoCBA_renamed_5.ufboot.ale.uml_rec
Calculating consensus tree.
terminate called after throwing an instance of 'bpp::Exception'
  what():  Trying to build a tree from incompatible bipartitions
```

So, it only outputs a single file. Although it should be enough, I still wonder what problem is it? It looks like that it should not a setting problem?

Here is the species tree and ale file.
[stree and treelist.zip](https://github.com/ssolo/ALE/files/8748745/stree.and.treelist.zip)

Thanks!

**Comment by V-Varga** [comment]
Hello! 

I'm very sorry to bother, but I wondered whether you had perhaps found a solution to this issue? 

I have run into the same error message, whether using `ALEml_undated` or `ALEmcmc_undated`. Similarly to the Newick file you shared, I have a species tree topology that initially branches into two larger clades, with no single dedicated outgroup taxon. 

I am using a Singularity build of the Docker image to run ALE v0.4. 

Thank you very much for any suggestions you may be able to provide!

**Comment by 444thLiao** [comment]
Sorry for that. I haven't found a solution yet. This error might be some kinds of unknown scenarios which are not considered by the authors.

But I think you could try other software or parse the intermediate output to get the result.

In my point of view, if you are stuck in this error, you must get the output file with `.uml_rec` as suffix when using `ALEml_undated`. The error it generated only occurred before combining all the reconciled gene trees. Thus, you could parse the file `.uml_rec` to interpret each reconciled tree and summary them by yourself. 

For me, actually, I try the other software such as GenRax and Ranger

**Comment by ssolo** [comment]
The error is coming from the Bio++ libraries consensus tree building. Using the current version compiled from github I don't get an error, as the consensus tree output has been disabled. @444thLiao's answer is also correct, the output .uml_rec is complete and usable, only thing missing is consensus tree. I attach the output for your files. 
[output.zip](https://github.com/ssolo/ALE/files/8925633/output.zip)

**Comment by V-Varga** [comment]
Thank you both very much for your responses and advice! 

I will proceed to parsing the .uml_rec file, then. I sincerely appreciate your help!
