### ISSUE TITLE
ALEml doesnot generate consensus tree

### ISSUE THREAD

**Issue by meiranmeiran** [ssolo/ALE#34]
Hi folks,

I compiled ALE from source on Ubuntu. Everything runs well except that ALEml_undated does not generate a consensus tree of the reconciled gene tree. When I run the same command and the same data on docker, a consensus tree is generated. I am wondering what is the cause?

Thanks,
Ran

command: 
'/home/apps/ALE/build/bin/ALEml_undated' species_tree.newick geneFamily.treelist.ale sample=1000

stdout: 
ALEml_undated using ALE v1.0
Read species tree from: species_tree.newick..
- 86 nodes loaded.
Read summary of tree sample for 4000 trees from: geneFamily.treelist.ale..
\ 367 nodes loaded.
Reconciliation model initialised, starting DTL rate optimisation..
#optimizing delta rate
#optimizing tau rate
#optimizing lambda rate
#optimizing rates
Optimizing... - 76
ML rates:  delta=1.12315e-08; tau=0.13238; lambda=0.349294.
LL=-171.526
Sampling reconciled gene trees..

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Results in: species_tree.newick_geneFamily.treelist.ale.uml_rec
Transfers in: species_tree.newick_geneFamily.treelist.ale.uTs

**Comment by ssolo** [comment]
We had issues with the bio++ library used for consensus tree generation and disabled this feature.

Gergely

**Comment by meiranmeiran** [comment]
Gergely,

Thanks for your quick reply. Does that mean the consensus tree generated by ALE at docker have some issue too?

Ran

**Comment by ssolo** [comment]
No, the issue was a hard to resolve / predict segmentation fault, when you get a tree it should be fine.
