### ISSUE TITLE
Presence probabilities

### ISSUE THREAD

**Issue by meiranmeiran** [ssolo/ALE#35]
Hi folks,

I was reading some papers that used ALE and they sometimes reported presence probabilities - a value that represents the likelihood of a gene present at an internal node in the specie tree. I am wondering where is the value found from the output of ALE. Is it from the '# of Originations' or 'opies' in the ump_rec file? Or there is another command (not ALEml_undated) that generates it?

Thanks in advance,
Ran

**Comment by ssolo** [comment]
I think it is now in the current version, please verify.
