### ISSUE TITLE
Error, file 1000 does not seem accessible.

### ISSUE THREAD

**Issue by Biscuite-wzy** [ssolo/ALE#37]
Hi,
I am using the program ALEobserve to create a geneFamily.ale file with example data. My comand is:
docker run -v $PWD:$PWD -w $PWD boussau/alesuite ALEobserve $PWD/HBG745965_real.1.treelist 1000.
However, I met a error, i.e. Error, file 1000 does not seem accessible. How can I discard the first 1000 trees as burnin? I hope I can get your help. Thanks.

**Comment by ssolo** [comment]
Like so:

~/src/ALE/build/bin/ALEobserve ~/src/ALE/example_data/HBG745965_real.1.treelist burnin=1000

Best,

Gergely


> On 29 Sep 2022, at 10:55, SuperY ***@***.***> wrote:
> 
> 
> Hi,
> I am using the program ALEobserve to create a geneFamily.ale file with example data. My comand is:
> docker run -v $PWD:$PWD -w $PWD boussau/alesuite ALEobserve $PWD/HBG745965_real.1.treelist 1000.
> However, I met a error, i.e. Error, file 1000 does not seem accessible. How can I discard the first 1000 trees as burnin? I hope I can get your help. Thanks.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 



---------------------------------------------
Dr. Gergely J Szöllősi

MTA-ELTE ,,Lendület”
Evolutionary Genomics Research Group
ERC “GENECLOCKS” Research Group
head researcher
http://ssolo.web.elte.hu
Tel: 00 36 30 725 35 32
---------------------------------------------

**Comment by Biscuite-wzy** [comment]
Hi,


I wonder how to use Docker to&nbsp;
discard the first 1000 trees as burnin. I hope I can get your help. Thanks.





787117923
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssolo/ALE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 晚上7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssolo/ALE] Error, file 1000 does not seem accessible. (Issue #37)





 Like so:
 
 ~/src/ALE/build/bin/ALEobserve ~/src/ALE/example_data/HBG745965_real.1.treelist burnin=1000
 
 Best,
 
 Gergely
 
 
 &gt; On 29 Sep 2022, at 10:55, SuperY ***@***.***&gt; wrote:
 &gt; 
 &gt; 
 &gt; Hi,
 &gt; I am using the program ALEobserve to create a geneFamily.ale file with example data. My comand is:
 &gt; docker run -v $PWD:$PWD -w $PWD boussau/alesuite ALEobserve $PWD/HBG745965_real.1.treelist 1000.
 &gt; However, I met a error, i.e. Error, file 1000 does not seem accessible. How can I discard the first 1000 trees as burnin? I hope I can get your help. Thanks.
 &gt; 
 &gt; —
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; 
 
 
 
 ---------------------------------------------
 Dr. Gergely J Szöllősi
 
 MTA-ELTE ,,Lendület”
 Evolutionary Genomics Research Group
 ERC “GENECLOCKS” Research Group
 head researcher
 http://ssolo.web.elte.hu
 Tel: 00 36 30 725 35 32
 ---------------------------------------------
