### ISSUE TITLE
Inferred frequencies greater than 1

### ISSUE THREAD

**Issue by 473021677** [ssolo/ALE#38]
Hi,
I am using ALEml_undated in ALE 1.0 package to infer the evolutionary history. No errors have been reported by the program. When I check the result files, I find that few inferred frequencies of duplications, transfers, losses, and originations are greater than 1. I am not sure if there's something wrong with it. I will use the threshold of 0.3 in the raw reconciliation frequencies to avoid misses of true events. Could I count these duplications, transfers, losses, and originations events with inferred frequencies greater than 1? I really need your help. Thanks very much.  

Best regards,
YangYuan

**Comment by ssolo** [comment]
The numbers in question are estimates of the posterior mean number of events and as a result can be larger than unity.

E.g. if there is a 50% posterior probability of 0 Ds on a branch and 50% probability of 1 D one gets 0.5, but if there is 50% probability of 1 D and 50% of 2 Ds then one has 1.5.


I.e. the table at the end of the .uml_rec file summarises the number events per branch in the species tree from the reconciled gene trees above it (the long list of Newick strings). These reconciled gene trees are sampled according to their joint sequence and reconciliation likelihood (cf. eq. 3 here https://academic.oup.com/sysbio/article/62/6/901/1711882 ) in general they can have different topologies and reconciliations (i.e. series of DTL events).

In the example I attach (which I got by running ../build/bin/ALEml_undated Sab.tree Gab.tree.ale delta=0.2 tau=0.1 i.e. by forcing a higher probability of duplication for the purposes of this toy example ) in the list of reconciled gene trees you can see several alternative reconciled gene trees, e.g.

ones with 3 duplications on branch 3 of the species tree, these are the branches on the reconciled gene tree with ***@***.***”: 

***@***.******@***.******@***.***:1).4:0;

and also ones with only one duplication on branch 3 of the species tree ***@***.***" again) and three transfers ***@***.***>3”, ***@***.***>3” and ***@***.***>c")

***@***.******@***.******@***.******@***.***>c:1).3:0;

etc.

the the estimate of the posterior mean number of D events on branch 3 of S is the average over these:

# of     Duplications   Transfers       Losses  Originations    copies  singletons      extinction_prob presence        LL
..
S_internal_branch       3       1.75    0.43    0       0.47    3.05    0.3     9.31127e-07     0.93    -10.8095
..

**Comment by 473021677** [comment]
Thanks&nbsp;for&nbsp;your&nbsp;explanation.&nbsp;I&nbsp;have&nbsp;got&nbsp;your&nbsp;idea.&nbsp;

Best&nbsp;regards,
Yang&nbsp;Yuan



&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;---原始邮件---
***@***.***&gt;
发送时间:2022年11月1日(星期二)&nbsp;晚上6:27
***@***.***&gt;;
主题:&nbsp;[ssolo/ALE]&nbsp;Inferred&nbsp;frequencies&nbsp;greater&nbsp;than&nbsp;1&nbsp;(Issue&nbsp;#38)


&nbsp;T&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
------------------&nbsp;Original&nbsp;------------------
From:&nbsp;&quot;Gergely J ***@***.***&gt;
Date:&nbsp;Tue, Nov 1, 2022 06:27 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [ssolo/ALE] Inferred frequencies greater than 1 (Issue #38)

**Comment by 473021677** [comment]
Dear Gergely
&nbsp; &nbsp; I have another question. I have 11 gene tree files (OG0000000.muscle.trimal.phy_renamed.treefile,&nbsp;OG0000001.muscle.trimal.phy_renamed.treefile, ...,&nbsp;OG0000010.muscle.trimal.phy_renamed.treefile) and 1 rooted species tree (Species_rooted_tree_newick_renamed.txt), and&nbsp;placed them into the same folder. Then, I run the ALE program using the commands like "ALEobserve&nbsp;OG0000000.muscle.trimal.phy_renamed.treefile" and&nbsp;ALEml_undated&nbsp;Species_rooted_tree_newick_renamed.txt&nbsp;OG0000000.muscle.trimal.phy_renamed.treefile.ale&nbsp;sample=100&nbsp; separators="_". For the four gene tree files including&nbsp;OG0000000.muscle.trimal.phy_renamed.treefile,&nbsp;OG0000001.muscle.trimal.phy_renamed.treefile,&nbsp;OG0000002.muscle.trimal.phy_renamed.treefile and&nbsp;OG0000003.muscle.trimal.phy_renamed.treefile, the errors "ALEml_undated using ALE v1.0&nbsp;Read species tree from: Species_rooted_tree_newick_renamed.txt..&nbsp;Error, file test/OG0000001.muscle.trimal.phy_renamed.treefile.ale does not seem accessible." have been reported by the program. However, for the other 7 gene tree files, no errors have been reported. I can't resolve this problem and need your help. I have appended the files. Thanks.


Best regards,
Yang Yuan&nbsp;&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Nov 1, 2022 06:27 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ssolo/ALE] Inferred frequencies greater than 1 (Issue #38)

&nbsp;



 The numbers in question are estimates of the posterior mean number of events and as a result can be larger than unity.
 
 E.g. if there is a 50% posterior probability of 0 Ds on a branch and 50% probability of 1 D one gets 0.5, but if there is 50% probability of 1 D and 50% of 2 Ds then one has 1.5.
 
 
 I.e. the table at the end of the .uml_rec file summarises the number events per branch in the species tree from the reconciled gene trees above it (the long list of Newick strings). These reconciled gene trees are sampled according to their joint sequence and reconciliation likelihood (cf. eq. 3 here https://academic.oup.com/sysbio/article/62/6/901/1711882 ) in general they can have different topologies and reconciliations (i.e. series of DTL events).
 
 In the example I attach (which I got by running ../build/bin/ALEml_undated Sab.tree Gab.tree.ale delta=0.2 tau=0.1 i.e. by forcing a higher probability of duplication for the purposes of this toy example ) in the list of reconciled gene trees you can see several alternative reconciled gene trees, e.g.
 
 ones with 3 duplications on branch 3 of the species tree, these are the branches on the reconciled gene tree with ***@***.***”: 
 
 ***@***.******@***.******@***.***:1).4:0;
 
 and also ones with only one duplication on branch 3 of the species tree ***@***.***" again) and three transfers ***@***.***&gt;3”, ***@***.***&gt;3” and ***@***.***&gt;c")
 
 ***@***.******@***.******@***.******@***.***&gt;c:1).3:0;
 
 etc.
 
 the the estimate of the posterior mean number of D events on branch 3 of S is the average over these:
 
 # of     Duplications   Transfers       Losses  Originations    copies  singletons      extinction_prob presence        LL
 ..
 S_internal_branch       3       1.75    0.43    0       0.47    3.05    0.3     9.31127e-07     0.93    -10.8095
 ..
 
 
 
 
 
 
 &gt; On 31 Oct 2022, at 03:51, 袁洋 ***@***.***&gt; wrote:
 &gt; 
 &gt; Dear Gergely
 &gt;    Thanks for your explanations. I still can't understand what the 1 D and 2 Ds mean. I guess that 1 D and 2 Ds mean that a gene family can be duplicated once and twice on the branch of the species phylogeny, respectively. If it is true, how I should deal with these duplication events with inferred frequencies greater than 1? And If the inferred frequency is 1.9, I am not sure whether one or two duplication event should be counted. 
 &gt; 
 &gt; Best regards,
 &gt; Yang Yuan
 &gt; 
 &gt; 
 &gt; ------------------ Original ------------------
 &gt; From:  "Gergely ***@***.***&gt;;
 &gt; Date:  Sun, Oct 30, 2022 05:31 PM
 &gt; To:  ***@***.***&gt;;
 &gt; Cc:  ***@***.***&gt;;
 &gt; Subject:  Re: Inferred frequencies greater than 1 (ALEml_undated in ALE 1.0 package)
 &gt; 
 &gt; 
 &gt; Dear Yang Yuan,
 &gt; 
 &gt; The numbers in question are estimates of the posterior mean number of events and as a result can be larger than unity.
 &gt; 
 &gt; E.g. if ther is a 50% posterior probality of 0 Ds on a branch and 50% probability of 1 D one gets 0.5, but if there is 50% probality of 1 D and 50% of 2 Ds then one has 1.5.
 &gt; 
 &gt; Hope this answers the question.
 &gt; 
 &gt; Gergely 
 &gt;&gt; On 2022. Oct 29., at 16:55, 袁洋 ***@***.***&gt; wrote:
 &gt;&gt; 
 &gt;&gt; ﻿
 &gt;&gt; Hi,
 &gt;&gt; I am using ALEml_undated in ALE 1.0 package to infer the evolutionary history. No errors have been reported by the program. When I check the result files, I find that few inferred frequencies of duplications, transfers, losses, and originations are greater than 1. I am not sure if there's something wrong with it. I will use the threshold of 0.3 in the raw reconciliation frequencies to avoid misses of true events. Could I count these duplications, transfers, losses, and originations events with inferred frequencies greater than 1? I really need your help. If you could help, I really appreciate. I have appended the result files. Thanks very much. 
 &gt;&gt; 
 &gt;&gt; Best regards,
 &gt;&gt; YangYuan
 &gt;&gt; 
 
 
 
 &gt; On 29 Oct 2022, at 17:00, 473021677 ***@***.***&gt; wrote:
 &gt; 
 &gt; 
 &gt; Hi,
 &gt; I am using ALEml_undated in ALE 1.0 package to infer the evolutionary history. No errors have been reported by the program. When I check the result files, I find that few inferred frequencies of duplications, transfers, losses, and originations are greater than 1. I am not sure if there's something wrong with it. I will use the threshold of 0.3 in the raw reconciliation frequencies to avoid misses of true events. Could I count these duplications, transfers, losses, and originations events with inferred frequencies greater than 1? I really need your help. Thanks very much.
 &gt; 
 &gt; Best regards,
 &gt; YangYuan
 &gt; 
 &gt; —
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; You are receiving this because you are subscribed to this thread.
 &gt;
