### ISSUE TITLE
ALE installation

### ISSUE THREAD

**Issue by ag8525** [ssolo/ALE#4]
Hello,

I am trying to install and use ALE on computer cluster. Is there any detailed and easy manual to install and run the program?

Specifically, the make command is looking for Bpp/Numeric/Random.all file which does not exist in bpp libraries. Any suggestions?

I would really appreciate any help,

Thank you

**Comment by ssolo** [comment]
@ag8525 we are working on detailed and easy instructions. 

Re, the issue you cite, to compile ALE you will need the Bio++ libraries, which you can install as described here:  http://biopp.univ-montp2.fr/wiki/index.php/Installation

**Comment by drenal** [comment]
Dear ag8525,

Does your issue still persist?

We created a [HowTo](https://github.com/ssolo/ALE/blob/opensuse/OpenSUSE-install.md) for openSUSE systems and it's a good starting point for other distributions too.

The Random.all-bug was resolved with commit [d6f5a40](https://github.com/ssolo/ALE/commit/d6f5a402d983da068c9e4b4bcae8b9f026ed1ecd).

Regards,
Lenard

**Comment by ssolo** [comment]
I'm closing this no the assumption that it has been resolved. Please  reopen if this is not the case.
