### ISSUE TITLE
tau flag not working?

### ISSUE THREAD

**Issue by HGord2022** [ssolo/ALE#40]
Hi there,

I'm hoping to use this great package to improve my gene tree, so I'm running ALEml_undated and using the tau=0 flag, however my .uml_rec file outputs this:

"# of	 Duplications	Transfers	Losses	Speciations"
Total 	19	396	386	39

Which shows the number of transfers as 396, which should not be possible if I am understanding this correctly. Any clarity on this would be really useful. the command I'm using is as follows:

$ ALEml_undated species.tree final.ufboot.ale tau=0

All the best,
Harry

**Comment by ssolo** [comment]
Could you provide the input files?On 2023. Apr 17., at 20:38, HGord2022 ***@***.***> wrote:﻿
Hi there,
I'm hoping to use this great package to improve my gene tree, so I'm running ALEml_undated and using the tau=0 flag, however my .uml_rec file outputs this:
of	 Duplications	Transfers	Losses	Speciations
Total 	19	396	386	39
Which shows the number of transfers as 396, which should not be possible if I am understanding this correctly. Any clarity on this would be really useful. the command I'm using is as follows:
$ ALEml_undated species.tree final.ufboot.ale tau=0
All the best,
Harry

**Comment by HGord2022** [comment]
Hi there,

Thanks so much for looking into this, I think I have just fixed the issue by using a completely bifurcating species tree to reconcile, my initial one had some multifurcations. I can still attach my initial input files if it would be helpful.

Thanks again,
Harry

**Comment by ssolo** [comment]
Fixed, please verify.
