### ISSUE TITLE
fractionMissing.h is missing

### ISSUE THREAD

**Issue by maxemil** [ssolo/ALE#8]
Hej @Boussau,
I just saw that you pushed an update to include fraction of missing genes in incomplete genomes! That's great! However, i guess its still a work in progress, as i am unable to build ALE with docker, getting the folowing error:
```
-- Configuring done
CMake Error at src/CMakeLists.txt:14 (add_library):
  Cannot find source file:

    fractionMissing.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

-- Build files have been written to: /usr/local/ALE/build
```

also, i needed to change the first RUN command in the Dockerfile to 
```
RUN apt-get update && apt-get clean
```

as i was getting
```
Step 3 : RUN apt-get clean && apt-get update
 ---> Running in b640adeb8f08
E: Could not open lock file /var/cache/apt/archives/lock - open (2: No such file or directory)
E: Unable to lock the download directory
The command '/bin/sh -c apt-get clean && apt-get update' returned a non-zero code: 100
```

excited to try out the version that deals with incomplete genomes!

**Comment by Boussau** [comment]
Hi Max Emil,

Sorry about the mess, I just pushed the two files. Regarding the docker, I'll look into it tomorrow.
Thanks for your messages and sorry again!

Bastien

**Comment by maxemil** [comment]
Hi Bastien,
Thanks for the quick reply! It compiles well now!
I will start testing with some of our data now, but i am wondering what would be the syntax of the `fractionMissing.txt` file? Something like this for all leaves present?:
```
genome1<tab>0.1
genome2<tab>0.05
...
```
And then I would invoke with `ALEml_undated $species_tree $ale_object fraction_missing="fractionMissing.txt"`?

thanks again for the work!

**Comment by Boussau** [comment]
Hi Max Emil, 

It would be:
genome1:0.1
genome2:0.05
...
but I have yet to test it! So far all I checked was that the results were still the same as before when the fraction of missing genes was not provided, I have not yet checked what happens when they are provided...

**Comment by maxemil** [comment]
Hi Bastien,
great! It runs fine so far with a sample file that i created, but i still have to see how the real data behaves and what changes in comparison to the previous version.

/max emil
