### ISSUE TITLE
Example Data Set - Segfault after DTL rate optimisation started

### ISSUE THREAD

**Issue by Hoembi** [ssolo/ALE#9]
Hi, 

I installed ALE on my MAC and was able to compile all binaries apart from the openmp (which should not be required to run the e.g. ALEml if I understand correctly). I used the commit: 693cdfcfae9e79759eabe7703094ab5a75a34a31 due to the problems fo the missing file in the newer commits.

To test my installation I run the example data sets according to the manual, but I always get a Segementation fault right after `Reconciliation model initialised, starting DTL rate optimisation..`.

I did a quick check with the precompiled binaries of the prance-branch and I observe the exact same SegFault error at the same position. 

Am I missing some crucial step or has someone else observed this behavior before?

**Comment by Boussau** [comment]
Something similar happened to me when I had compiled Bio++ using Clang but ALE using the Gnu compiler. Could that be the reason? You can compile Bio++ (and ALE) using a cmake command similar to this:
cd build
cmake .. -DCMAKE_C_COMPILER=/usr/local/Cellar/gcc/7.1.0/bin/gcc-7 -DCMAKE_CXX_COMPILER=/usr/local/Cellar/gcc/7.1.0/bin/g++-7

These specific paths to gcc and g++ were those I got by using brew to install these compilers.

**Comment by Hoembi** [comment]
Thanks, I made sure to compile everything with the same compiler, using openmpi-gcc6, and the binaries work now fine on the example data set.  (I had the right compiler installed before but since it was installed with macports I did not activate it and instead compiled it with the apple clang).
